### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by voducman** [tailin1009/DualHead-Network#1]
Can you release full implementation for the paper?

**Comment by tailin1009** [comment]
> Can you release full implementation for the paper?

Yes, please wait a while. Our code is on the way. ^_^

**Comment by tailin1009** [comment]
> Can you release full implementation for the paper?

Yes, please wait for a while. Our code is on the way.

**Comment by wdkhuans** [comment]
come on

**Comment by sankamohotttala** [comment]
Hi, would you be able to share the code? Your paper is really cool and I think will have a considerable impact on the future research as well. Thanks.

**Comment by MikuuGithub** [comment]
> Hi, would you be able to share the code? Your paper is really cool and I think will have a considerable impact on the future research as well. Thanks.


I also look forward to!

**Comment by LiuXuChao-HEU** [comment]
Please，come on!

**Comment by wys2929** [comment]
Hi, would you be able to share the code? Your paper is really cool and I think will have a considerable impact on the future research as well. Thanks.

**Comment by tailin1009** [comment]
Hi all! I'm so sorry about the delay.

I just release the code and I tried to make them clean and easy to run. If you have any problems, please let me know.
