### ISSUE TITLE
ModuleNotFoundError: No module named 'data_gen_2sagcn'

### ISSUE THREAD

**Issue by SunPengP** [tailin1009/DualHead-Network#3]
ModuleNotFoundError: No module named 'data_gen_2sagcn'

**Comment by tailin1009** [comment]
Sorry about the mistake. 
Please change `data_gen_2sagcn` to `data_gen`

<img width="466" alt="image" src="https://user-images.githubusercontent.com/44869667/200509774-3499fcd3-a24d-4370-80aa-67b4b5ca3069.png">

**Comment by SunPengP** [comment]
ok, thank you

**Comment by SunPengP** [comment]
> Sorry about the mistake. Please change `data_gen_2sagcn` to `data_gen`
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/44869667/200509774-3499fcd3-a24d-4370-80aa-67b4b5ca3069.png">

ok,thank you
